project_id = "swfnnrpzpkdypbrzmgnr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[functions.generate-qr-shortlink]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false