-- Migration: Create dealership logos storage bucket and add thumbnail column
-- Description: Set up infrastructure for dealership logo uploads with thumbnail generation
-- Created: 2025-10-22

-- ============================================================================
-- 1. CREATE STORAGE BUCKET FOR DEALERSHIP LOGOS
-- ============================================================================

-- Create bucket for dealership logos (public access for display performance)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'dealership-logos',
  'dealership-logos',
  true, -- Public access for fast logo display
  2097152, -- 2MB limit (logos should be small)
  ARRAY['image/jpeg', 'image/jpg', 'image/png', 'image/webp', 'image/svg+xml']
)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 2. ADD THUMBNAIL COLUMN TO DEALERSHIPS TABLE
-- ============================================================================

-- Add thumbnail_logo_url column to store Edge Function generated thumbnails
ALTER TABLE dealerships
ADD COLUMN IF NOT EXISTS thumbnail_logo_url text;

COMMENT ON COLUMN dealerships.logo_url IS 'Full-size logo URL (client-compressed to max 512px, ~200KB)';
COMMENT ON COLUMN dealerships.thumbnail_logo_url IS 'Thumbnail logo URL (server-generated 400px, ~25KB) for performance';

-- ============================================================================
-- 3. ROW LEVEL SECURITY POLICIES
-- ============================================================================

-- Policy 1: Allow authenticated users to READ all dealership logos (public display)
CREATE POLICY "Public read access for dealership logos"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'dealership-logos');

-- Policy 2: Allow dealers to UPLOAD their own logo
-- Security: Only members of a dealership can upload to their folder
CREATE POLICY "Dealers can upload their own logo"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'dealership-logos' AND
  (storage.foldername(name))[1]::int IN (
    SELECT dealer_id FROM dealer_memberships WHERE user_id = auth.uid() AND is_active = true
  )
);

-- Policy 3: Allow dealers to UPDATE their own logo
CREATE POLICY "Dealers can update their own logo"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'dealership-logos' AND
  (storage.foldername(name))[1]::int IN (
    SELECT dealer_id FROM dealer_memberships WHERE user_id = auth.uid() AND is_active = true
  )
);

-- Policy 4: Allow dealers to DELETE their own logo
CREATE POLICY "Dealers can delete their own logo"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'dealership-logos' AND
  (storage.foldername(name))[1]::int IN (
    SELECT dealer_id FROM dealer_memberships WHERE user_id = auth.uid() AND is_active = true
  )
);

-- ============================================================================
-- 4. INDEXES FOR PERFORMANCE
-- ============================================================================

-- Index on logo_url for faster lookups (if needed)
CREATE INDEX IF NOT EXISTS idx_dealerships_logo_url
ON dealerships(logo_url)
WHERE logo_url IS NOT NULL;

-- Index on thumbnail_logo_url for faster lookups
CREATE INDEX IF NOT EXISTS idx_dealerships_thumbnail_logo_url
ON dealerships(thumbnail_logo_url)
WHERE thumbnail_logo_url IS NOT NULL;

-- ============================================================================
-- STORAGE STRUCTURE:
-- dealership-logos/
--   ├── {dealer_id}/
--   │   ├── logo_{timestamp}.jpg       # Full size (max 512x512, compressed)
--   │   └── logo_{timestamp}_thumb.jpg # Thumbnail (400x400, generated by Edge Function)
-- ============================================================================
