-- =====================================================
-- UPDATE INVOICE NUMBER CONSTRAINT
-- Date: 2025-11-02
-- Description: Update CHECK constraint to accept 2-digit year format (YY instead of YYYY)
-- =====================================================

-- Drop the old constraint
ALTER TABLE public.invoices
DROP CONSTRAINT IF EXISTS invoice_number_format;

-- Add the new constraint with 2-digit year format
ALTER TABLE public.invoices
ADD CONSTRAINT invoice_number_format
CHECK (invoice_number ~ '^INV-[0-9]{2}-[0-9]+$');

-- Do the same for payments table if it has a similar constraint
ALTER TABLE public.payments
DROP CONSTRAINT IF EXISTS payment_number_format;

ALTER TABLE public.payments
ADD CONSTRAINT payment_number_format
CHECK (payment_number ~ '^PAY-[0-9]{2}-[0-9]+$');

-- =====================================================
-- NOTES:
-- =====================================================
-- OLD CONSTRAINT: invoice_number ~ '^INV-[0-9]{4}-[0-9]+$'
--   Accepted: INV-2025-0001, INV-2025-0002
--   Pattern:  INV-YYYY-####
--
-- NEW CONSTRAINT: invoice_number ~ '^INV-[0-9]{2}-[0-9]+$'
--   Accepts:  INV-25-0001, INV-25-0002, INV-26-0001
--   Pattern:  INV-YY-####
--
-- This matches the format generated by the updated
-- generate_invoice_number() and generate_payment_number() functions
-- =====================================================
