/**
 * Report Export Utilities
 *
 * Professional PDF and Excel report generation for DetailHub module.
 * Supports payroll reports, attendance reports, hours worked reports.
 *
 * Features:
 * - PDF export with jsPDF + autoTable
 * - Excel export with ExcelJS
 * - Professional styling and formatting
 * - Summary sections with KPIs
 * - Multi-page support
 * - Landscape orientation for wide tables
 *
 * @module reportExporters
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import ExcelJS from 'exceljs';
import { format } from 'date-fns';

// =====================================================
// TYPE DEFINITIONS
// =====================================================

/**
 * Report data structure for export
 */
export interface ReportData {
  /** Report title (e.g., "Payroll Report") */
  title: string;

  /** Subtitle or description (e.g., "Jan 1 - Jan 31, 2025") */
  subtitle?: string;

  /** Date range in formatted string */
  dateRange: string;

  /** Dealership name */
  dealershipName: string;

  /** Generated timestamp */
  generatedAt: string;

  /** Table column headers */
  headers: string[];

  /** Table data rows */
  rows: (string | number)[][];

  /** Optional summary metrics */
  summary?: {
    label: string;
    value: string | number;
  }[];

  /** Optional chart data (for future enhancement) */
  chartData?: any;
}

/**
 * Export options for customization
 */
export interface ExportOptions {
  /** Page orientation */
  orientation?: 'portrait' | 'landscape';

  /** Include summary section */
  includeSummary?: boolean;

  /** Include company logo */
  includeLogo?: boolean;

  /** Footer text */
  footerText?: string;
}

// =====================================================
// PDF EXPORT
// =====================================================

/**
 * Export report to PDF format
 *
 * Creates a professional PDF with:
 * - Company header with dealership name
 * - Report title and metadata
 * - Formatted table with alternating row colors
 * - Summary section with KPIs
 * - Page numbers and watermark
 *
 * @param data - Report data to export
 * @param options - Export customization options
 *
 * @example
 * ```tsx
 * exportReportToPDF({
 *   title: 'Payroll Report',
 *   subtitle: 'January 2025',
 *   dealershipName: 'ABC Motors',
 *   dateRange: 'Jan 1 - Jan 31, 2025',
 *   generatedAt: new Date().toLocaleString(),
 *   headers: ['Employee', 'Hours', 'Pay'],
 *   rows: [['John Doe', 160, '$2400']],
 *   summary: [{ label: 'Total Hours', value: 160 }]
 * });
 * ```
 */
export function exportReportToPDF(
  data: ReportData,
  options: ExportOptions = {}
): void {
  const {
    orientation = 'landscape',
    includeSummary = true,
    footerText = 'Generated by MyDetailArea'
  } = options;

  // Create new PDF document (landscape for wide tables)
  const doc = new jsPDF({
    orientation,
    unit: 'mm',
    format: 'letter'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  let currentY = margin;

  // =============================
  // HEADER SECTION
  // =============================

  // Company/Dealership name (top right)
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(data.dealershipName, pageWidth - margin, currentY, { align: 'right' });
  currentY += 6;

  // Report title (large, bold)
  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text(data.title, margin, currentY);
  currentY += 10;

  // Subtitle and metadata
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);

  if (data.subtitle) {
    doc.text(data.subtitle, margin, currentY);
    currentY += 6;
  }

  doc.setFontSize(9);
  doc.text(`Date Range: ${data.dateRange}`, margin, currentY);
  currentY += 5;
  doc.text(`Generated: ${data.generatedAt}`, margin, currentY);
  currentY += 10;

  // =============================
  // TABLE SECTION
  // =============================

  // Determine if last row is a totals row (typically all-caps or starts with "TOTAL")
  const lastRow = data.rows[data.rows.length - 1];
  const hasTotalsRow = lastRow &&
    (String(lastRow[0]).toUpperCase().includes('TOTAL') ||
     String(lastRow[0]).toUpperCase() === String(lastRow[0]));

  autoTable(doc, {
    startY: currentY,
    head: [data.headers],
    body: data.rows,
    theme: 'striped',
    headStyles: {
      fillColor: [55, 65, 81], // Gray-700 (Notion-style)
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10,
      halign: 'left'
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
      textColor: [0, 0, 0],
      lineColor: [229, 231, 235], // Gray-200
      lineWidth: 0.1
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251] // Gray-50 (subtle)
    },
    // Bold the totals row if present
    didParseCell: (data) => {
      if (hasTotalsRow && data.row.index === data.table.body.length - 1) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = [243, 244, 246]; // Gray-100
      }
    },
    margin: { left: margin, right: margin },
    tableWidth: 'auto'
  });

  // Get final Y position after table
  currentY = (doc as any).lastAutoTable.finalY + 10;

  // =============================
  // SUMMARY SECTION (Optional)
  // =============================

  if (includeSummary && data.summary && data.summary.length > 0) {
    // Add spacing before summary
    if (currentY > pageHeight - 50) {
      doc.addPage();
      currentY = margin;
    }

    // Summary section title
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Summary', margin, currentY);
    currentY += 8;

    // Summary boxes in grid layout
    const boxWidth = 55;
    const boxHeight = 18;
    const boxSpacing = 5;
    const itemsPerRow = Math.floor((pageWidth - 2 * margin) / (boxWidth + boxSpacing));

    data.summary.forEach((item, index) => {
      const col = index % itemsPerRow;
      const row = Math.floor(index / itemsPerRow);
      const x = margin + col * (boxWidth + boxSpacing);
      const y = currentY + row * (boxHeight + boxSpacing);

      // Draw box with subtle border
      doc.setDrawColor(229, 231, 235); // Gray-200
      doc.setFillColor(249, 250, 251); // Gray-50
      doc.roundedRect(x, y, boxWidth, boxHeight, 2, 2, 'FD');

      // Label (small, gray)
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(107, 114, 128); // Gray-500
      doc.text(item.label, x + 3, y + 5);

      // Value (large, bold, black)
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 0);
      doc.text(String(item.value), x + 3, y + 13);
    });

    currentY += Math.ceil(data.summary.length / itemsPerRow) * (boxHeight + boxSpacing) + 5;
  }

  // =============================
  // FOOTER SECTION
  // =============================

  const totalPages = doc.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Page number
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );

    // Watermark
    doc.text(
      footerText,
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
  }

  // =============================
  // SAVE FILE
  // =============================

  const fileName = `${sanitizeFileName(data.title)}_${format(new Date(), 'yyyy-MM-dd_HHmm')}.pdf`;
  doc.save(fileName);
}

// =====================================================
// EXCEL EXPORT
// =====================================================

/**
 * Export report to Excel format
 *
 * Creates a professional Excel workbook with:
 * - Formatted header section
 * - Data table with styled headers
 * - Summary sheet with KPIs
 * - Auto-sized columns
 * - Number formatting
 * - Conditional formatting (optional)
 *
 * @param data - Report data to export
 * @param options - Export customization options
 *
 * @example
 * ```tsx
 * exportReportToExcel({
 *   title: 'Payroll Report',
 *   subtitle: 'January 2025',
 *   dealershipName: 'ABC Motors',
 *   dateRange: 'Jan 1 - Jan 31, 2025',
 *   generatedAt: new Date().toLocaleString(),
 *   headers: ['Employee', 'Hours', 'Pay'],
 *   rows: [['John Doe', 160, 2400]],
 *   summary: [{ label: 'Total Hours', value: 160 }]
 * });
 * ```
 */
export async function exportReportToExcel(
  data: ReportData,
  options: ExportOptions = {}
): Promise<void> {
  const {
    includeSummary = true
  } = options;

  // Create new workbook
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'MyDetailArea';
  workbook.created = new Date();

  // =============================
  // DATA SHEET
  // =============================

  const dataSheet = workbook.addWorksheet('Report Data', {
    views: [{ state: 'frozen', ySplit: 5 }] // Freeze header rows
  });

  // Add report header section
  let currentRow = 1;

  // Title row
  const titleRow = dataSheet.getRow(currentRow);
  titleRow.getCell(1).value = data.title;
  titleRow.getCell(1).font = { size: 16, bold: true };
  titleRow.height = 25;
  currentRow++;

  // Subtitle row
  if (data.subtitle) {
    const subtitleRow = dataSheet.getRow(currentRow);
    subtitleRow.getCell(1).value = data.subtitle;
    subtitleRow.getCell(1).font = { size: 12 };
    currentRow++;
  }

  // Metadata rows
  const metaRow1 = dataSheet.getRow(currentRow);
  metaRow1.getCell(1).value = `Date Range: ${data.dateRange}`;
  metaRow1.getCell(1).font = { size: 10, color: { argb: 'FF6B7280' } }; // Gray-500
  currentRow++;

  const metaRow2 = dataSheet.getRow(currentRow);
  metaRow2.getCell(1).value = `Dealership: ${data.dealershipName}`;
  metaRow2.getCell(1).font = { size: 10, color: { argb: 'FF6B7280' } };
  currentRow++;

  const metaRow3 = dataSheet.getRow(currentRow);
  metaRow3.getCell(1).value = `Generated: ${data.generatedAt}`;
  metaRow3.getCell(1).font = { size: 10, color: { argb: 'FF6B7280' } };
  currentRow += 2; // Add blank row

  // Add table headers
  const headerRow = dataSheet.getRow(currentRow);
  data.headers.forEach((header, index) => {
    const cell = headerRow.getCell(index + 1);
    cell.value = header;
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF374151' } // Gray-700
    };
    cell.border = {
      top: { style: 'thin' },
      left: { style: 'thin' },
      bottom: { style: 'thin' },
      right: { style: 'thin' }
    };
    cell.alignment = { vertical: 'middle', horizontal: 'left' };
  });
  headerRow.height = 20;
  currentRow++;

  // Add data rows
  const dataStartRow = currentRow;
  data.rows.forEach((row, rowIndex) => {
    const dataRow = dataSheet.getRow(currentRow);
    row.forEach((cell, colIndex) => {
      const excelCell = dataRow.getCell(colIndex + 1);

      // Detect numeric values for proper formatting
      if (typeof cell === 'number') {
        excelCell.value = cell;
        // Apply number format (2 decimal places for hours)
        if (data.headers[colIndex].toLowerCase().includes('hour')) {
          excelCell.numFmt = '0.00';
        } else if (data.headers[colIndex].toLowerCase().includes('pay') ||
                   data.headers[colIndex].toLowerCase().includes('$')) {
          excelCell.numFmt = '$#,##0.00';
        }
      } else {
        excelCell.value = cell;
      }

      // Borders
      excelCell.border = {
        top: { style: 'thin', color: { argb: 'FFE5E7EB' } },
        left: { style: 'thin', color: { argb: 'FFE5E7EB' } },
        bottom: { style: 'thin', color: { argb: 'FFE5E7EB' } },
        right: { style: 'thin', color: { argb: 'FFE5E7EB' } }
      };

      // Alternate row shading
      if (rowIndex % 2 === 0) {
        excelCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF9FAFB' } // Gray-50
        };
      }
    });

    // Bold the last row if it's a totals row
    const firstCellValue = String(row[0]).toUpperCase();
    if (firstCellValue.includes('TOTAL') || firstCellValue === String(row[0])) {
      data.headers.forEach((_, colIndex) => {
        dataRow.getCell(colIndex + 1).font = { bold: true };
      });
    }

    currentRow++;
  });

  // Auto-size columns
  dataSheet.columns.forEach((column, index) => {
    let maxLength = data.headers[index].length;

    data.rows.forEach(row => {
      const cellValue = String(row[index] || '');
      maxLength = Math.max(maxLength, cellValue.length);
    });

    column.width = Math.min(Math.max(maxLength + 2, 12), 40);
  });

  // Add auto-filter to header row
  const tableRange = `A${dataStartRow - 1}:${String.fromCharCode(64 + data.headers.length)}${currentRow - 1}`;
  dataSheet.autoFilter = tableRange;

  // =============================
  // SUMMARY SHEET (Optional)
  // =============================

  if (includeSummary && data.summary && data.summary.length > 0) {
    const summarySheet = workbook.addWorksheet('Summary');

    // Title
    const summaryTitleRow = summarySheet.getRow(1);
    summaryTitleRow.getCell(1).value = 'Report Summary';
    summaryTitleRow.getCell(1).font = { size: 14, bold: true };
    summaryTitleRow.height = 20;

    // Headers
    const summaryHeaderRow = summarySheet.getRow(3);
    summaryHeaderRow.getCell(1).value = 'Metric';
    summaryHeaderRow.getCell(2).value = 'Value';
    summaryHeaderRow.font = { bold: true };
    summaryHeaderRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF374151' }
    };
    summaryHeaderRow.eachCell((cell) => {
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // Summary data
    data.summary.forEach((item, index) => {
      const row = summarySheet.getRow(4 + index);
      row.getCell(1).value = item.label;
      row.getCell(2).value = item.value;

      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin', color: { argb: 'FFE5E7EB' } },
          left: { style: 'thin', color: { argb: 'FFE5E7EB' } },
          bottom: { style: 'thin', color: { argb: 'FFE5E7EB' } },
          right: { style: 'thin', color: { argb: 'FFE5E7EB' } }
        };
      });
    });

    // Auto-size columns
    summarySheet.getColumn(1).width = 30;
    summarySheet.getColumn(2).width = 20;
  }

  // =============================
  // SAVE FILE
  // =============================

  const fileName = `${sanitizeFileName(data.title)}_${format(new Date(), 'yyyy-MM-dd_HHmm')}.xlsx`;
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  });

  // Trigger download
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}

// =====================================================
// UTILITY FUNCTIONS
// =====================================================

/**
 * Sanitize filename by removing invalid characters
 */
function sanitizeFileName(fileName: string): string {
  return fileName
    .replace(/[^a-z0-9_\-]/gi, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
}

/**
 * Format date range for display
 */
export function formatDateRange(from: Date, to: Date): string {
  return `${format(from, 'MMM dd, yyyy')} - ${format(to, 'MMM dd, yyyy')}`;
}

/**
 * Format hours with 2 decimal places
 */
export function formatHours(hours: number): string {
  return hours.toFixed(2);
}

/**
 * Format currency with $ prefix
 */
export function formatCurrency(amount: number): string {
  return `$${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

/**
 * Calculate sum of array values
 */
export function sum(values: number[]): number {
  return values.reduce((acc, val) => acc + val, 0);
}
